[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci"]
cacheDirectories = ["node_modules/.cache"]

[phases.build]
cmds = [
    "npm run build",
    "cp -r .next/static .next/standalone/.next/static",
    "cp -r public .next/standalone/public"
]
cacheDirectories = ["node_modules/.cache", ".next/cache"]

[start]
cmd = "HOSTNAME=0.0.0.0 node .next/standalone/server.js"
