[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
    "npm run build",
    "cp -r .next/static .next/standalone/.next/static",
    "cp -r public .next/standalone/public"
]

[start]
cmd = "WS_NO_BUFFER_UTIL=1 WS_NO_UTF_8_VALIDATE=1 HOSTNAME=0.0.0.0 node .next/standalone/server.js"
